### ISSUE TITLE
binascii.Error: Invalid base64-encoded string

### ISSUE THREAD

**Issue by huwentao** [TyrantLucifer/ssr-command-client#10]
linux Fedora
python main.py

Traceback (most recent call last):
  File "main.py", line 77, in <module>
    main()
  File "main.py", line 37, in main
    update_ssr_list_info()
  File "/usr/local/share/ssr-commend-client/funtions.py", line 70, in update_ssr_list_info
    ssr_info_dict_list = generate_ssr_info_dict_list(ssr_url_list)
  File "/usr/local/share/ssr-commend-client/utils.py", line 140, in generate_ssr_info_dict_list
    ssr_info_dict = analysis_ssr_url(ssr_url)
  File "/usr/local/share/ssr-commend-client/utils.py", line 121, in analysis_ssr_url
    ssr_dict[key] = base64decode(value)
  File "/usr/local/share/ssr-commend-client/utils.py", line 73, in base64decode
    return base64.urlsafe_b64decode(text).decode()
  File "/usr/lib64/python3.8/base64.py", line 133, in urlsafe_b64decode
    return b64decode(s)
  File "/usr/lib64/python3.8/base64.py", line 87, in b64decode
    return binascii.a2b_base64(s)
binascii.Error: Invalid base64-encoded string: number of data characters (1) cannot be 1 more than a multiple of 4

**Comment by TyrantLucifer** [comment]
这个问题是因为你的ssr订阅链接里的节点信息不正常，请检查你自己的订阅链接，谢谢。

**Comment by TyrantLucifer** [comment]
@huwentao  Hi, 请在项目文件夹下执行git pull更新一下,这个问题已经解决,看看你那边是否能够正确更新订阅列表
