### ISSUE TITLE
无法添加订阅链接

### ISSUE THREAD

**Issue by ziyic** [TyrantLucifer/ssr-command-client#23]
终端输出如下：
2020-12-27 17:56:41,046 - ParseUtils.py[line:111] - [requestUrl] - INFO: start parse ssr subcribe: https://pptp.cloud/sub/0lQ3Uw4IAn949200.html
2020-12-27 17:56:46,956 - ParseUtils.py[line:117] - [requestUrl] - ERROR: string argument should contain only ASCII characters
2020-12-27 17:56:46,956 - ParseUtils.py[line:118] - [requestUrl] - ERROR: Parse subscribe url error

系统：Archlinux
python版本：Python 3.9.1

**Comment by ziyic** [comment]
尝试使用root 用户，仍无法添加
Traceback (most recent call last):
  File "/home/ziyic/ssr-command-client/main.py", line 8, in <module>
    from funcitions.Functions import *
  File "/home/ziyic/ssr-command-client/funcitions/Functions.py", line 3, in <module>
    from utils.ParseUtils import *
  File "/home/ziyic/ssr-command-client/utils/ParseUtils.py", line 7, in <module>
    from utils.SSRTestUtils import *
  File "/home/ziyic/ssr-command-client/utils/SSRTestUtils.py", line 7, in <module>
    import socks
ModuleNotFoundError: No module named 'socks'

**Comment by TyrantLucifer** [comment]
好的，已经收到，等我查看一下

**Comment by TyrantLucifer** [comment]
不需要用root用户，普通用户就可以，不介意的话你把你的订阅链接给我，我在我这里测一下，我刚才测了一下你上面发的那个地址，请求出来是空的

**Comment by ziyic** [comment]
> 不需要用root用户，普通用户就可以，不介意的话你把你的订阅链接给我，我在我这里测一下，我刚才测了一下你上面发的那个地址，请求出来是空的

https://pptp.cloud/sub/QlQ3Uw4IAn9492OQ.html

**Comment by TyrantLucifer** [comment]
![image](https://user-images.githubusercontent.com/51053924/103172063-b76d9c00-488b-11eb-9bc9-baf5408d02c4.png)我这里可以更新没问题，你执行一下`python3 main.py --setting-url https://pptp.cloud/sub/QlQ3Uw4IAn9492OQ.html`，然后再执行`python3 main.py -u`

**Comment by ziyic** [comment]
➜  ssr-command-client git:(2.0) python3 main.py --setting-url https://pptp.cloud/sub/QlQ3Uw4IAn9492OQ.html
2020-12-27 21:40:48,260 - Functions.py[line:123] - [updateSubcribeUrl] - INFO: change subscribe url to: https://pptp.cloud/sub/QlQ3Uw4IAn9492OQ.html
➜  ssr-command-client git:(2.0) python3 main.py -u                                                        
2020-12-27 21:41:04,375 - ParseUtils.py[line:111] - [requestUrl] - INFO: start parse ssr subcribe: https://pptp.cloud/sub/QlQ3Uw4IAn9492OQ.html
2020-12-27 21:41:31,181 - ParseUtils.py[line:117] - [requestUrl] - ERROR: string argument should contain only ASCII characters
2020-12-27 21:41:31,181 - ParseUtils.py[line:118] - [requestUrl] - ERROR: Parse subscribe url error
Traceback (most recent call last):
  File "/home/ziyic/ssr-command-client/main.py", line 103, in <module>
    main()
  File "/home/ziyic/ssr-command-client/main.py", line 58, in main
    u.updateSubscribe()
  File "/home/ziyic/ssr-command-client/funcitions/Functions.py", line 115, in updateSubscribe
    ssrInfoList = u.update(i.ssrListJsonFile,
  File "/home/ziyic/ssr-command-client/logger/Logging.py", line 13, in main
    content = func(*args)
  File "/home/ziyic/ssr-command-client/utils/ParseUtils.py", line 147, in update
    for ssrUrl in urlResult:
TypeError: 'NoneType' object is not iterable

**Comment by ziyic** [comment]
<img width="1581" alt="截屏2020-12-27 下午9 44 08" src="https://user-images.githubusercontent.com/31206158/103172198-affac280-488c-11eb-9d3f-eb0ba7036747.png">

**Comment by TyrantLucifer** [comment]
可能是python版本的问题，你尝试用3.8及以下试试，我还没用过

**Comment by ziyic** [comment]
我这边试了python2 也不太行（Arch安装老版本太麻烦了。。。）
<img width="1537" alt="截屏2020-12-27 下午11 11 05" src="https://user-images.githubusercontent.com/31206158/103173917-fbb36900-4898-11eb-91c5-b78df3b4e996.png">

**Comment by TyrantLucifer** [comment]
我自己装个新版的试试，找一下bug所在。

**Comment by TyrantLucifer** [comment]
你尝试一下二进制文件，看看可以吗？https://github.com/TyrantLucifer/ssr-command-client/releases/download/v2.0.1/ssr-command-client_linux_amd64
