### ISSUE TITLE
UPDATE SUBSCRIPTION ERROR

### ISSUE THREAD

**Issue by Fater20** [TyrantLucifer/ssr-command-client#24]
yuheng@yuheng-desktop:~/ssr-command-client$ python3 main.py -u
2021-01-01 19:02:30,644 - ParseUtils.py[line:111] - [requestUrl] - INFO: start parse ssr subcribe: https://tyrantlucifer.com/ssr/ssr.txt
2021-01-01 19:02:32,020 - ParseUtils.py[line:111] - [requestUrl] - INFO: start parse ssr subcribe: https://
Traceback (most recent call last):
  File "main.py", line 103, in <module>
    main()
  File "main.py", line 58, in main
    u.updateSubscribe()
  File "/home/yuheng/ssr-command-client/funcitions/Functions.py", line 116, in updateSubscribe
    settings.valueDict['subscribe_url'].split('|'))
  File "/home/yuheng/ssr-command-client/logger/Logging.py", line 13, in main
    content = func(*args)
  File "/home/yuheng/ssr-command-client/utils/ParseUtils.py", line 151, in update
    ssrInfo['id'] = self.ssrInfoList.index(ssrInfo)
TypeError: 'NoneType' object does not support item assignment

**Comment by Fater20** [comment]
你好，我导入订阅链接后在更新订阅时出现了以上错误，能帮忙看一下问题吗，谢谢。

**Comment by TyrantLucifer** [comment]
在项目目录下使用`git pull`更新一下，然后再执行`python3 main.py -u`进行更新

**Comment by TyrantLucifer** [comment]
更新完版本之后，可以了吗？如果有新的进展，请麻烦告知我

**Comment by Fater20** [comment]
可以了，万分感谢。

**Comment by TyrantLucifer** [comment]
好的，我关掉这个issue了
