### ISSUE TITLE
解析ssr链接bug，在/?后面无数据的情况下出现数组越界错误

### ISSUE THREAD

**Issue by WeyNiDrop** [TyrantLucifer/ssr-command-client#33]
Traceback (most recent call last):
  File "/usr/local/bin/shadowsocksr-cli", line 11, in <module>
    load_entry_point('shadowsocksr-cli==2.1.0', 'console_scripts', 'shadowsocksr-cli')()
  File "/usr/local/lib/python3.6/site-packages/shadowsocksr_cli/main.py", line 79, in main
    UpdateConfigurations.add_shadowsocksr_by_url(args.add_ssr)
  File "/usr/local/lib/python3.6/site-packages/shadowsocksr_cli/functions.py", line 114, in add_shadowsocksr_by_url
    update_shadowsocksr.add_shadowsocksr_by_url(ssr_url)
  File "/usr/local/lib/python3.6/site-packages/shadowsocksr_cli/update_utils.py", line 53, in add_shadowsocksr_by_url
    ssr_dict = ParseShadowsocksr.parse_shadowsocksr(ssr_url)
  File "/usr/local/lib/python3.6/site-packages/shadowsocksr_cli/parse_utils.py", line 76, in parse_shadowsocksr
    value = params.split('=')[1]
IndexError: list index out of range

**Comment by TyrantLucifer** [comment]
请提供详细的ssr全链接或者订阅链接，我需要看一下你的ssr链接长啥样，这样我好定位一下哪里需要优化，后面一般是混淆参数，我修复完之后你可以在机场修改订阅。
