### ISSUE TITLE
开启本地http代理失败

### ISSUE THREAD

**Issue by Zhangkc** [TyrantLucifer/ssr-command-client#55]
```
$ shadowsocksr-cli --http start
2021-12-23 10:04:41,749 - http_utils.py[line:292] - [__download_pac_template] - INFO: Start download pac template...
Traceback (most recent call last):
  File "/home/cloud/.local/lib/python3.6/site-packages/urllib3/connectionpool.py", line 696, in urlopen
    self._prepare_proxy(conn)
  File "/home/cloud/.local/lib/python3.6/site-packages/urllib3/connectionpool.py", line 964, in _prepare_proxy
    conn.connect()
  File "/home/cloud/.local/lib/python3.6/site-packages/urllib3/connection.py", line 371, in connect
    self._tunnel()
  File "/usr/lib/python3.6/http/client.py", line 934, in _tunnel
    (version, code, message) = response._read_status()
  File "/usr/lib/python3.6/http/client.py", line 302, in _read_status
    raise BadStatusLine(line)
http.client.BadStatusLine: 

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/cloud/.local/lib/python3.6/site-packages/requests/adapters.py", line 449, in send
    timeout=timeout
  File "/home/cloud/.local/lib/python3.6/site-packages/urllib3/connectionpool.py", line 756, in urlopen
    method, url, error=e, _pool=self, _stacktrace=sys.exc_info()[2]
  File "/home/cloud/.local/lib/python3.6/site-packages/urllib3/util/retry.py", line 532, in increment
    raise six.reraise(type(error), error, _stacktrace)
  File "/home/cloud/.local/lib/python3.6/site-packages/urllib3/packages/six.py", line 769, in reraise
    raise value.with_traceback(tb)
  File "/home/cloud/.local/lib/python3.6/site-packages/urllib3/connectionpool.py", line 696, in urlopen
    self._prepare_proxy(conn)
  File "/home/cloud/.local/lib/python3.6/site-packages/urllib3/connectionpool.py", line 964, in _prepare_proxy
    conn.connect()
  File "/home/cloud/.local/lib/python3.6/site-packages/urllib3/connection.py", line 371, in connect
    self._tunnel()
  File "/usr/lib/python3.6/http/client.py", line 934, in _tunnel
    (version, code, message) = response._read_status()
  File "/usr/lib/python3.6/http/client.py", line 302, in _read_status
    raise BadStatusLine(line)
urllib3.exceptions.ProtocolError: ('Connection aborted.', BadStatusLine('\x05\x00',))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/cloud/.local/bin/shadowsocksr-cli", line 11, in <module>
    sys.exit(main())
  File "/home/cloud/.local/lib/python3.6/site-packages/shadowsocksr_cli/main.py", line 100, in main
    HandleHttpServer.handle_http_server(args.http, args.port, args.http_port)
  File "/home/cloud/.local/lib/python3.6/site-packages/shadowsocksr_cli/functions.py", line 412, in handle_http_server
    HandleHttpServer.start(local_port, http_port=http_port)
  File "/home/cloud/.local/lib/python3.6/site-packages/shadowsocksr_cli/functions.py", line 397, in start
    GeneratePac.generate_pac(Setting.get_value("local_address"), local_port)
  File "/home/cloud/.local/lib/python3.6/site-packages/shadowsocksr_cli/http_utils.py", line 301, in generate_pac
    GeneratePac.__download_pac_template()
  File "/home/cloud/.local/lib/python3.6/site-packages/shadowsocksr_cli/http_utils.py", line 293, in __download_pac_template
    result = requests.get('https://tyrantlucifer.com/ssr/autoproxy.pac')
  File "/home/cloud/.local/lib/python3.6/site-packages/requests/api.py", line 75, in get
    return request('get', url, params=params, **kwargs)
  File "/home/cloud/.local/lib/python3.6/site-packages/requests/api.py", line 61, in request
    return session.request(method=method, url=url, **kwargs)
  File "/home/cloud/.local/lib/python3.6/site-packages/requests/sessions.py", line 542, in request
    resp = self.send(prep, **send_kwargs)
  File "/home/cloud/.local/lib/python3.6/site-packages/requests/sessions.py", line 655, in send
    r = adapter.send(request, **kwargs)
  File "/home/cloud/.local/lib/python3.6/site-packages/requests/adapters.py", line 498, in send
    raise ConnectionError(err, request=request)
requests.exceptions.ConnectionError: ('Connection aborted.', BadStatusLine('\x05\x00',))
```
挺奇怪的，浏览器下载https://tyrantlucifer.com/ssr/autoproxy.pac可以成功

**Comment by TyrantLucifer** [comment]
请问使用的ssr-command-client的版本号是多少

**Comment by TyrantLucifer** [comment]
![image](https://user-images.githubusercontent.com/51053924/147185682-27977e0b-11d7-465d-a439-9aa8f4c0e13e.png)
我本地是没有问题的
