### ISSUE TITLE
Dependency problem when upgrade python

### ISSUE THREAD

**Issue by nilknow** [TyrantLucifer/ssr-command-client#57]
Part of error is shown above:
`  
File "/home/pg/.local/lib/python3.10/site-packages/shadowsocksr_cli/shadowsocks/lru_cache.py", line 45, in <module>
    class LRUCache(collections.MutableMapping):
AttributeError: module 'collections' has no attribute 'MutableMapping'
`

The whole error log follow:
`
Traceback (most recent call last):
  File "/home/pg/.local/bin/shadowsocksr-cli", line 33, in <module>
    sys.exit(load_entry_point('shadowsocksr-cli==2.1.6', 'console_scripts', 'shadowsocksr-cli')())
  File "/home/pg/.local/bin/shadowsocksr-cli", line 25, in importlib_load_entry_point
    return next(matches).load()
  File "/usr/lib/python3.10/importlib/metadata/__init__.py", line 162, in load
    module = import_module(match.group('module'))
  File "/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/pg/.local/lib/python3.10/site-packages/shadowsocksr_cli/main.py", line 11, in <module>
    from shadowsocksr_cli.functions import *
  File "/home/pg/.local/lib/python3.10/site-packages/shadowsocksr_cli/functions.py", line 11, in <module>
    from shadowsocksr_cli.common import *
  File "/home/pg/.local/lib/python3.10/site-packages/shadowsocksr_cli/common.py", line 11, in <module>
    from shadowsocksr_cli.update_utils import *
  File "/home/pg/.local/lib/python3.10/site-packages/shadowsocksr_cli/update_utils.py", line 12, in <module>
    from shadowsocksr_cli.network_test_utils import *
  File "/home/pg/.local/lib/python3.10/site-packages/shadowsocksr_cli/network_test_utils.py", line 14, in <module>
    from shadowsocksr_cli.handle_utils import *
  File "/home/pg/.local/lib/python3.10/site-packages/shadowsocksr_cli/handle_utils.py", line 11, in <module>
    from shadowsocksr_cli.shadowsocks import daemon, eventloop, tcprelay, udprelay, asyncdns
  File "/home/pg/.local/lib/python3.10/site-packages/shadowsocksr_cli/shadowsocks/daemon.py", line 25, in <module>
    from shadowsocksr_cli.shadowsocks import common, shell
  File "/home/pg/.local/lib/python3.10/site-packages/shadowsocksr_cli/shadowsocks/common.py", line 26, in <module>
    from shadowsocksr_cli.shadowsocks import lru_cache
  File "/home/pg/.local/lib/python3.10/site-packages/shadowsocksr_cli/shadowsocks/lru_cache.py", line 45, in <module>
    class LRUCache(collections.MutableMapping):
AttributeError: module 'collections' has no attribute 'MutableMapping'
Traceback (most recent call last):
  File "/home/pg/.local/bin/shadowsocksr-cli", line 33, in <module>
    sys.exit(load_entry_point('shadowsocksr-cli==2.1.6', 'console_scripts', 'shadowsocksr-cli')())
  File "/home/pg/.local/bin/shadowsocksr-cli", line 25, in importlib_load_entry_point
    return next(matches).load()
  File "/usr/lib/python3.10/importlib/metadata/__init__.py", line 162, in load
    module = import_module(match.group('module'))
  File "/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/pg/.local/lib/python3.10/site-packages/shadowsocksr_cli/main.py", line 11, in <module>
    from shadowsocksr_cli.functions import *
  File "/home/pg/.local/lib/python3.10/site-packages/shadowsocksr_cli/functions.py", line 11, in <module>
    from shadowsocksr_cli.common import *
  File "/home/pg/.local/lib/python3.10/site-packages/shadowsocksr_cli/common.py", line 11, in <module>
    from shadowsocksr_cli.update_utils import *
  File "/home/pg/.local/lib/python3.10/site-packages/shadowsocksr_cli/update_utils.py", line 12, in <module>
    from shadowsocksr_cli.network_test_utils import *
  File "/home/pg/.local/lib/python3.10/site-packages/shadowsocksr_cli/network_test_utils.py", line 14, in <module>
    from shadowsocksr_cli.handle_utils import *
  File "/home/pg/.local/lib/python3.10/site-packages/shadowsocksr_cli/handle_utils.py", line 11, in <module>
    from shadowsocksr_cli.shadowsocks import daemon, eventloop, tcprelay, udprelay, asyncdns
  File "/home/pg/.local/lib/python3.10/site-packages/shadowsocksr_cli/shadowsocks/daemon.py", line 25, in <module>
    from shadowsocksr_cli.shadowsocks import common, shell
  File "/home/pg/.local/lib/python3.10/site-packages/shadowsocksr_cli/shadowsocks/common.py", line 26, in <module>
    from shadowsocksr_cli.shadowsocks import lru_cache
  File "/home/pg/.local/lib/python3.10/site-packages/shadowsocksr_cli/shadowsocks/lru_cache.py", line 45, in <module>
    class LRUCache(collections.MutableMapping):
AttributeError: module 'collections' has no attribute 'MutableMapping'
`

If you don't have time, I might have some time to fix it.

This is a great project, thanks for your attribution : )

**Comment by TyrantLucifer** [comment]
It seems that some api changed in python3.10. So far the project has only been tested in Python environments up to version 3.9 so I can't locate the bug where is. I used the error log you provided to search for a post that seemed to solve the problem:
https://stackoverflow.com/questions/69512672/getting-attributeerror-module-collections-has-no-attribute-mutablemapping-w
Maybe it could solve your problem. Thank you for your support. If you have any questions, you can leave a comment below.

**Comment by nilknow** [comment]
My SSR GUI client also has this issue. It seem to be a 底层依赖(don't know how to say it in English, 哈哈哈) problem, and hard to fix from your side. Maybe the only way to fix it is to downgrade the python version. I think this issue should be closed now. Thanks for your help.
