### ISSUE TITLE
执行shadowsocksr-cli -u的时候出错

### ISSUE THREAD

**Issue by songshuhan** [TyrantLucifer/ssr-command-client#60]
2022-03-15 07:29:17,984 - parse_utils.py[line:113] - [parse_shadowsocksr_by_subscribe_url] - INFO: Start parse ssr subscribe url: https://newsub.zjnyd.top/link/WZKa0vxR2tTCaCHm?sub=1
2022-03-15 07:31:26,126 - parse_utils.py[line:122] - [parse_shadowsocksr_by_subscribe_url] - ERROR: HTTPSConnectionPool(host='newsub.zjnyd.top', port=443): Max retries exceeded with url: /link/WZKa0vxR2tTCaCHm?sub=1 (Caused by NewConnectionError('<requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0x7fabc503a240>: Failed to establish a new connection: [Errno 110] Connection timed out',))
2022-03-15 07:31:26,127 - parse_utils.py[line:123] - [parse_shadowsocksr_by_subscribe_url] - ERROR: Parse subscribe url https://newsub.zjnyd.top/link/WZKa0vxR2tTCaCHm?sub=1 error
Traceback (most recent call last):
  File "/home/songsh/anaconda3/anaconda3_install/envs/dgl_env/bin/shadowsocksr-cli", line 8, in <module>
    sys.exit(main())
  File "/home/songsh/anaconda3/anaconda3_install/envs/dgl_env/lib/python3.6/site-packages/shadowsocksr_cli/main.py", line 59, in main
    UpdateConfigurations.update_subscribe()
  File "/home/songsh/anaconda3/anaconda3_install/envs/dgl_env/lib/python3.6/site-packages/shadowsocksr_cli/functions.py", line 114, in update_subscribe
    update_shadowsocksr.update()
  File "/home/songsh/anaconda3/anaconda3_install/envs/dgl_env/lib/python3.6/site-packages/shadowsocksr_cli/logger.py", line 52, in main
    func(*args, **kwargs)
  File "/home/songsh/anaconda3/anaconda3_install/envs/dgl_env/lib/python3.6/site-packages/shadowsocksr_cli/update_utils.py", line 41, in update
    self.ssr_dict_list = ShadowsocksrTest.connect_thread_pool(self.ssr_dict_list)
  File "/home/songsh/anaconda3/anaconda3_install/envs/dgl_env/lib/python3.6/site-packages/shadowsocksr_cli/network_test_utils.py", line 71, in connect_thread_pool
    pool = Pool(len(ssr_dict_list))
  File "/home/songsh/anaconda3/anaconda3_install/envs/dgl_env/lib/python3.6/multiprocessing/context.py", line 119, in Pool
    context=self.get_context())
  File "/home/songsh/anaconda3/anaconda3_install/envs/dgl_env/lib/python3.6/multiprocessing/pool.py", line 167, in __init__
    raise ValueError("Number of processes must be at least 1")
ValueError: Number of processes must be at least 1

**Comment by songshuhan** [comment]
换了订阅地址想更新订阅，但是一直不行，之前用的时候是可以的

**Comment by songshuhan** [comment]
还有个小问题是我再用curl的时候会出现<html><head><script language=javascript>location='http://gw.ict.ac.cn/index_1.html?url='+document.location;</script></head></html>，但是之前我使用的时候是可以显示完整的html信息的，不知道为什么突然变成这么显示了

**Comment by TyrantLucifer** [comment]
![image](https://user-images.githubusercontent.com/51053924/158296388-3f5a91a6-690f-4cb2-9177-2775a68f4501.png)

![image](https://user-images.githubusercontent.com/51053924/158296499-adb9752e-8db2-4b02-a823-e11c304bd9ea.png)

我这没有问题，出现这种情况是因为当时你的网络有问题，友情提示一下，你的订阅连接已经泄露在issue中，记得在后台自己改一下订阅链接
