### ISSUE TITLE
为什么提示这个，我库都导好了。。有ping3这个的

### ISSUE THREAD

**Issue by leemamas** [TyrantLucifer/ssr-command-client#9]
venv) [master][~/ssr-commend-client]$ pip list
Package     Version
----------- ----------
certifi     2020.4.5.1
chardet     3.0.4
colorama    0.4.3
genpac      2.1.0
idna        2.9
ping3       2.6.5
pip         20.1.1
prettytable 0.7.2
requests    2.23.0
setuptools  46.4.0
shadowsocks 2.8.2
urllib3     1.25.9
wheel       0.34.2
(venv) [master][~/ssr-commend-client]$ sudo python main.py -l
Traceback (most recent call last):
  File "main.py", line 5, in <module>
    from funtions import *
  File "/home/leemamas/ssr-commend-client/funtions.py", line 4, in <module>
    from utils import *
  File "/home/leemamas/ssr-commend-client/utils.py", line 10, in <module>
    import ping3
ModuleNotFoundError: No module named 'ping3'
(venv) [master][~/ssr-commend-client]$ 
(venv) [master][~/ssr-commend-client]$

**Comment by TyrantLucifer** [comment]
使用root安装ping3这个库呢？因为ping3需要root权限，你虚拟环境安装可能不行。

**Comment by leemamas** [comment]
ping3我是安装上了，不需要root都可以的，就是执行-l 或者 -u 任何的参数就会报错，提示没有ping3模块，我试过切换root权限下执行 也是不行，暂时未能解决！

**Comment by TyrantLucifer** [comment]
使用ping3需要root权限，使用sudo就好了呀。

**Comment by KumaCool** [comment]
我开始也与楼主报一样的错误.可能就是没有使用root权限,所以我重新运行了:
`sudo pip3 install -r requirement.txt`
然后我运行:
`sudo python3 main.py -u`
报以下错误
```
Being parsed the ssr url: https://raw.githubusercontent.com/satrom/V2SSR/master/SSR/Day.txt
It will take a moment,Please be patient~~
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/urllib3/connection.py", line 156, in _new_conn
    conn = connection.create_connection(
  File "/usr/lib/python3/dist-packages/urllib3/util/connection.py", line 84, in create_connection
    raise err
  File "/usr/lib/python3/dist-packages/urllib3/util/connection.py", line 74, in create_connection
    sock.connect(sa)
ConnectionRefusedError: [Errno 111] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 665, in urlopen
    httplib_response = self._make_request(
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 376, in _make_request
    self._validate_conn(conn)
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 996, in _validate_conn
    conn.connect()
  File "/usr/lib/python3/dist-packages/urllib3/connection.py", line 300, in connect
    conn = self._new_conn()
  File "/usr/lib/python3/dist-packages/urllib3/connection.py", line 168, in _new_conn
    raise NewConnectionError(
urllib3.exceptions.NewConnectionError: <urllib3.connection.VerifiedHTTPSConnection object at 0xffff807fa5e0>: Failed to establish a new connection: [Errno 111] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/requests/adapters.py", line 439, in send
    resp = conn.urlopen(
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 719, in urlopen
    retries = retries.increment(
  File "/usr/lib/python3/dist-packages/urllib3/util/retry.py", line 436, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='raw.githubusercontent.com', port=443): Max retries exceeded with url: /satrom/V2SSR/master/SSR/Day.txt (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0xffff807fa5e0>: Failed to establish a new connection: [Errno 111] Connection refused'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "main.py", line 80, in <module>
    main()
  File "main.py", line 38, in main
    update_ssr_list_info()
  File "/home/ubuntu/app/ssr-command-client/funtions.py", line 69, in update_ssr_list_info
    ssr_url_list += get_ssr_list(url)
  File "/home/ubuntu/app/ssr-command-client/utils.py", line 81, in get_ssr_list
    result = requests.get(url, headers = {'User-Agent':'Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/70.0.3538.25 Safari/537.36 Core/1.70.3742.400 QQBrowser/10.5.3864.400'})
  File "/usr/lib/python3/dist-packages/requests/api.py", line 75, in get
    return request('get', url, params=params, **kwargs)
  File "/usr/lib/python3/dist-packages/requests/api.py", line 60, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/lib/python3/dist-packages/requests/sessions.py", line 533, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/lib/python3/dist-packages/requests/sessions.py", line 646, in send
    r = adapter.send(request, **kwargs)
  File "/usr/lib/python3/dist-packages/requests/adapters.py", line 516, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='raw.githubusercontent.com', port=443): Max retries exceeded with url: /satrom/V2SSR/master/SSR/Day.txt (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0xffff807fa5e0>: Failed to establish a new connection: [Errno 111] Connection refused'))
```
系统是ubuntu server 20.04 LTS

请问 是什么原因?

**Comment by TyrantLucifer** [comment]
因为你没有修改默认的订阅链接，初始会设置一个默认的订阅链接，现在那个订阅链接失效了。

**Comment by KumaCool** [comment]
@TyrantLucifer 我修改了订阅地址,也尝试过删除后再添加...打印显示是正确的...但还是报以上错误.

**Comment by TyrantLucifer** [comment]
使用python main.py --setting-url url去重置你链接，在重置完之后，使用python main.py --list-url 查看链接是否设置成功。
